deployments:
- name: BASE
  enabled: true
  base_url: http://ftp.debian.org/debian/
  suite: trixie
  components: main contrib non-free non-free-firmware
  options: '[ Signed-By=/usr/share/keyrings/debian-archive-keyring.gpg ]'
  frozen: false
  included_attributes:
  - SET-All Systems
  excluded_attributes: []
  source: E
- name: BACKPORTS
  enabled: false
  base_url: http://ftp.debian.org/debian/
  suite: trixie-backports
  components: main contrib non-free non-free-firmware
  options: '[ Signed-By=/usr/share/keyrings/debian-archive-keyring.gpg ]'
  frozen: false
  included_attributes: []
  excluded_attributes: []
  source: E
- name: SECURITY
  enabled: true
  base_url: http://deb.debian.org/debian-security/
  suite: trixie-security
  components: main contrib non-free non-free-firmware
  options: '[ Signed-By=/usr/share/keyrings/debian-archive-keyring.gpg ]'
  frozen: false
  included_attributes:
  - SET-All Systems
  excluded_attributes: []
  source: E
- name: UPDATE
  enabled: true
  base_url: http://ftp.debian.org/debian/
  suite: trixie-updates
  components: main contrib non-free non-free-firmware
  options: '[ Signed-By=/usr/share/keyrings/debian-archive-keyring.gpg ]'
  frozen: false
  included_attributes:
  - SET-All Systems
  excluded_attributes: []
  source: E
- name: MIGASFREE
  enabled: true
  comment: Imported from migasfree-imports template
  available_packages:
  - migasfree-client
  - migasfree-play
  - migasfree-agent
  packages_to_install:
  - migasfree-agent
  - migasfree-client
  packages_to_remove: []
  included_attributes:
  - SET-All Systems
  excluded_attributes: []
  store: thirds
  source: I
- name: LXDE
  enabled: true
  comment: instala LXDE.
  available_packages: []
  packages_to_install:
  - lightdm
  - lxde-core
  - xorg
  - migasfree-play
  packages_to_remove: []
  included_attributes:
  - FLV-LXDE
  excluded_attributes: []
  store: thirds
  source: I
- name: KERNEL-GENERIC
  enabled: true
  comment: Kernel for Physical Hardware
  available_packages: []
  packages_to_install:
  - linux-image-amd64
  packages_to_remove: []
  included_attributes:
  - SET-All Systems
  excluded_attributes:
  - FLV-VIRTUAL
  store: thirds
  source: I
- name: KERNEL-VIRTUAL
  enabled: true
  comment: Kernel and tools for virtualizacion  (Proxmox, VMware, vSphere, Azure)
  available_packages: []
  packages_to_install:
  - cloud-guest-utils
  - cloud-init
  - linux-image-cloud-amd64
  - open-vm-tools
  - qemu-guest-agent
  packages_to_remove: []
  included_attributes:
  - FLV-VIRTUAL
  excluded_attributes: []
  store: thirds
  source: I
properties:
- prefix: FLV
  name: FLAVOURS
  enabled: false
  kind: N
  sort: server
  auto_add: true
  language: 0
  code: ''
  attributes:
  - value: LXDE
    description: 'LXDE: Lightweight X11 Desktop Environment'
  - value: VIRTUAL
    description: KERNEL for virtualization (qemu,kvm, proxmox,vsphere, azure, aws,
      ....)
- prefix: SET
  name: Attribute Set
  enabled: true
  kind: N
  sort: basic
  auto_add: true
  language: 1
  code: print 'All Systems'
  attributes:
  - value: All Systems
    description: All Systems Set Description
